import PropertiesProvider from '@/propertiesProvider/propertiesProvider';
import { Inter } from 'next/font/google';
import AuthProvider from '../../components/authProvider/authProvider';
import './globals.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <AuthProvider> */}
      <link href='https://fonts.googleapis.com/css?family=Alegreya Sans SC' rel='stylesheet'></link>
      <body className={inter.className}>

        <AuthProvider>
          <PropertiesProvider>
          {children}
          </PropertiesProvider>
          </AuthProvider>
        
        </body>
      <script src="https://cdn.tailwindcss.com"></script>
      <script src="https://kit.fontawesome.com/cacef5af72.js" crossorigin="anonymous"></script>
      {/* </AuthProvider> */}
    </html>
  )
}
